version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - localstack

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev
  
  localstack:
    container_name: localstack
    environment:
      # - DEBUG=1
      - AWS_ACCESS_KEY_ID=xyz
      - AWS_SECRET_ACCESS_KEY=aaa
      - AWS_DEFAULT_REGION=ap-south-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.aws/buckets.sh:/etc/localstack/init/ready.d/buckets.sh

  celery-redis:
    container_name: redis
    image: redis:alpine

  celery:
    container_name: celery
    restart: always
    build:
      context: ./server
      dockerfile: ./Celery.Dockerfile
    command: celery -A server worker -l info
    volumes:
      - ./server:/server
    env_file:
      - .env.dev
    depends_on:
      - db
      - celery-redis
      - server

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
