# Generated by Django 4.1.5 on 2023-03-26 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobAPI", "0003_alter_candidateapplication_applied_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "docker_file",
                    models.FileField(
                        upload_to="docker_files", verbose_name="Docker File"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Assignment Type",
                "verbose_name_plural": "Assignment Types",
            },
        ),
        migrations.CreateModel(
            name="CandidateAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_test_cases",
                    models.IntegerField(default=100, verbose_name="Total Test Cases"),
                ),
                (
                    "cutoff_test_cases",
                    models.IntegerField(default=75, verbose_name="Cutoff Test Cases"),
                ),
                ("active_from", models.DateTimeField(verbose_name="Active From")),
                ("active_upto", models.DateTimeField(verbose_name="Active Upto")),
                ("duration", models.DurationField(verbose_name="Duration")),
                ("expired", models.BooleanField(default=False, verbose_name="Expired")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "fk_assignment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_type",
                        to="assignmentAPI.assignmenttype",
                        verbose_name="Assignment Type",
                    ),
                ),
                (
                    "fk_job_posting_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobAPI.jobpostingsteps",
                        verbose_name="Job Posting Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Assignment",
                "verbose_name_plural": "Candidate Assignments",
            },
        ),
        migrations.CreateModel(
            name="CandidateAssignmentResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=256, null=True)),
                (
                    "test_cases_passed",
                    models.IntegerField(default=0, verbose_name="Test Cases Passed"),
                ),
                (
                    "attempted",
                    models.BooleanField(default=False, verbose_name="Attempted"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "fk_candidate_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_application",
                        to="jobAPI.candidateapplication",
                        verbose_name="Candidate Application",
                    ),
                ),
                (
                    "fk_candidate_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_assignment",
                        to="assignmentAPI.candidateassignment",
                        verbose_name="Candidate Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Assignment Result",
                "verbose_name_plural": "Candidate Assignment Results",
            },
        ),
    ]
