# Generated by Django 4.1.5 on 2023-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignmentAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateassignmentresult",
            name="assignment_files",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="Assignment Files"
            ),
        ),
        migrations.AlterField(
            model_name="candidateassignmentresult",
            name="container_id",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Container ID"
            ),
        ),
    ]
