# Generated by Django 4.1.5 on 2023-03-27 13:57

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignmentAPI", "0002_candidateassignmentresult_assignment_files_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmenttype",
            name="docker_file",
            field=models.FileField(
                upload_to=common.utils.dockerfile_upload_path,
                validators=[common.utils.validate_dockerfile],
                verbose_name="Docker File",
            ),
        ),
    ]
