# Generated by Django 4.1.5 on 2023-03-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobAPI", "0003_alter_candidateapplication_applied_at_and_more"),
        ("assignmentAPI", "0003_alter_assignmenttype_docker_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateassignment",
            name="fk_job_posting_step",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_assignment",
                to="jobAPI.jobpostingsteps",
                verbose_name="Job Posting Step",
            ),
        ),
        migrations.AlterField(
            model_name="candidateassignmentresult",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="candidateassignmentresult",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start Time"
            ),
        ),
    ]
