# Generated by Django 4.1.5 on 2023-01-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('rejected', models.BooleanField(default=False)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Application',
                'verbose_name_plural': 'Candidate Applications',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
            },
        ),
        migrations.CreateModel(
            name='JobPostingSteps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.IntegerField(choices=[(1, 'Applied'), (2, 'Assignment'), (3, 'Interview'), (4, 'Offer'), (5, 'Hired')], default=1)),
                ('step_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobAPI.jobposting')),
            ],
            options={
                'verbose_name': 'Job Posting Step',
                'verbose_name_plural': 'Job Posting Steps',
            },
        ),
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_job_posting_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='jobAPI.candidateapplication')),
                ('fk_job_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobAPI.jobpostingsteps')),
            ],
            options={
                'verbose_name': 'Candidate Status',
                'verbose_name_plural': 'Candidate Statuses',
            },
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='fk_job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobAPI.jobposting'),
        ),
    ]
