# Generated by Django 4.1.5 on 2023-02-17 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobAPI", "0003_alter_candidateapplication_applied_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateapplication",
            name="resume_keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
